name = "Zima's Vanilla+"
author = "zima"
version = "1.0.0.a2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a53d78fb3b4edfd08cb0f72252dc7ce21b6c29e421b9025ac71755a61489d6e3"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
