name = "Zima's Vanilla+"
author = "zima"
version = "1.0.0.a2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "353dc110ca9ee97bacb5b9bf60c5757457b367e0c6cec3f8dfe24a2725637b8c"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
