name = "Zima's Vanilla+"
author = "zima"
version = "1.0.0.a2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13bc075a111f9c1a5931695a3f7763adb93cb0235193e909a1d452d744bfe9ee"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
