name = "Zima's Vanilla+"
author = "zima"
version = "1.0.0.a2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e4a16997292091129a22b5fd813651279898a0d174a26325b3ccfa076d26411"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
