name = "Zima's Vanilla+"
author = "zima"
version = "1.1.0.a3+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa1f4bcbf831b2fc6d43c3cb250b4de7760b97a030b7fd015cb89abdcc7fc398"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
