name = "Zima's Vanilla+"
author = "zima"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1002ee88c0d0aa77396dcd0f1e07eba7f7ccab56cc0941c4f680fe41e1c54cad"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
